<?php
/**
 * @file
 * Bibliotek.dk custom search preprocess functions for combined form values.
 *
 * Since the form element ID's are different for each website,
 * the search pre-process and javascript attach functions need to be maintained seperately.
 */

/**
 * Implements hook_bibdk_custom_search_field_preprocess().
 */
function bibdk_custom_search_preprocess_bibdk_custom_search_field_preprocess($form_state) {
  dpm($form_state);
  $fields = array();
  if ( !isset($form_state['complete form']['#bibdk_pre_search_process']) ) {
    return $fields;
  }
  foreach ( $form_state['complete form']['#bibdk_pre_search_process'] as $element_id => $value_ids ) { // f.ex.: '4' => array('2','5')
    switch ($element_id) {
      case '35':
        if ( $form_state['values']['term36'] ) {
  dpm($form_state['values']['term36']);
          switch ($form_state['values']['term35']) {
            case 'year_gt':
              $fields[] = 'dc.date>' . $form_state['values']['term36'];
              break;
            case 'year_lt':
              $fields[] = 'dc.date<' . $form_state['values']['term36'];;
              break;
            case 'year_eq':
              $fields[] = 'dc.date=' . $form_state['values']['term36'];;
              break;
          }
        } else {
  dpm('no fields');
          return $fields;
        }
        break;
    }
  }
  dpm($fields);
  return $fields;
}


/**
 * Implements hook_bibdk_custom_search_add_js().
 */
function bibdk_custom_search_preprocess_bibdk_custom_search_add_js($element_ids=array()) {
  $js = array();
  foreach ( $element_ids as $element_id => $value_ids ) { // f.ex.: '4' => array('2','5')
    switch ($element_id) {
      case '35':
        $js[] = drupal_get_path('module', 'bibdk_custom_search_preprocess') . '/js/bibdk_custom_search_datepicker.js';
        break;
    }
  }
  return $js;
}
