<?php
/**
 * @file
 * Bibliotek.dk custom search preprocess functions for combined form values.
 *
 * Since the form element ID's are different for each website,
 * the search pre-process and javascript attach functions need to be maintained seperately.
 */

/**
 * Implements hook_bibdk_custom_search_field_preprocess().
 */
function bibdk_custom_search_preprocess_bibdk_custom_search_field_preprocess($form, $form_state) {
  $fields = array();
  if ( !isset($form['#bibdk_pre_search_process']) ) {
    return $fields;
  }
  foreach ( $form['#bibdk_pre_search_process'] as $element_id => $value_ids ) { // f.ex.: '4' => array('2','5')
    switch ($element_id) {
      case '6c70823e-0c81-c3d4-f9b8-716937b6c813':
        if ( $form_state['values']['term595cb75c-082c-4d74-f9f9-258957c66d55'] ) {
          switch ($form_state['values']['termdd18e670-8c1b-b154-4da8-3101c6a5101d']) {
            case 'year_gt':
              $fields[] = 'dkcclterm.år>' . $form_state['values']['term595cb75c-082c-4d74-f9f9-258957c66d55'];
              break;
            case 'year_lt':
              $fields[] = 'dkcclterm.år<' . $form_state['values']['term595cb75c-082c-4d74-f9f9-258957c66d55'];
              break;
            case 'year_eq':
              $fields[] = 'dkcclterm.år=' . $form_state['values']['term595cb75c-082c-4d74-f9f9-258957c66d55'];
              break;
          }
        }
        break;
      case 'webtest-element-1': // webtest case
        if ( $form_state['values']['termwebtest-value-1'] == 'default_value_test_1'
          && $form_state['values']['termwebtest-value-2'] == 'default_value_test_2' ) {
            $fields[] = 'webtest=default_value_test_1_2';
        }
        break;
    }
  }
  return $fields;
}


/**
 * Implements hook_bibdk_custom_search_add_js().
 */
function bibdk_custom_search_preprocess_bibdk_custom_search_add_js($element_ids=array()) {
  $js = array();
  foreach ( $element_ids as $element_id => $value_ids ) { // f.ex.: '4' => array('2','5')
    switch ($element_id) {
      case '35':
        $js[] = drupal_get_path('module', 'bibdk_custom_search_preprocess') . '/js/bibdk_custom_search_datepicker.js';
        break;
    }
  }
  return $js;
}
