<?php
/**
 * @file
 * Bibliotek.dk custom search preprocess functions for combined form values.
 *
 * Since the form element ID's are different for each website,
 * the search pre-process and javascript attach functions need to be maintained seperately.
 */

/**
 * Implements hook_bibdk_custom_search_field_preprocess().
 */
function bibdk_custom_search_preprocess_bibdk_custom_search_field_preprocess($form, $form_state) {
  $fields = array();
  if ( !isset($form['#bibdk_pre_search_process']) ) {
    return $fields;
  }
  foreach ( $form['#bibdk_pre_search_process'] as $element_id => $value_ids ) { // f.ex.: '4' => array('2','5')
    switch ($element_id) {
      case '35':
        if ( $form_state['values']['term36'] ) {
          switch ($form_state['values']['term35']) {
            case 'year_gt':
              $fields[] = 'dkcclterm.år >' . $form_state['values']['term36'];
              break;
            case 'year_lt':
              $fields[] = 'dkcclterm.år <' . $form_state['values']['term36'];;
              break;
            case 'year_eq':
              $fields[] = 'dkcclterm.år =' . $form_state['values']['term36'];;
              break;
          }
        }
        break;
      case '1': // webtest case
        if ( $form_state['values']['term1'] == 'default_value_test_1'
          && $form_state['values']['term2'] == 'default_value_test_2' ) {
            $fields[] = 'webtest=default_value_test_1_2';
        }
        break;
    }
  }
  return $fields;
}


/**
 * Implements hook_bibdk_custom_search_add_js().
 */
function bibdk_custom_search_preprocess_bibdk_custom_search_add_js($element_ids=array()) {
  $js = array();
  foreach ( $element_ids as $element_id => $value_ids ) { // f.ex.: '4' => array('2','5')
    switch ($element_id) {
      case '35':
        $js[] = drupal_get_path('module', 'bibdk_custom_search_preprocess') . '/js/bibdk_custom_search_datepicker.js';
        break;
    }
  }
  return $js;
}
